baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Ethan's Home"
# theme = 'anatole'  # Comment out or remove this line
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[module]
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"

